fix: update nonce generation to use cryptographic RNG
spruceid/siwe pull request #20
Opened 2021-11-24 02:29 UTC by kdenhartog

Small change to move the example implementation to a 96 bit nonce generated by a CSPRNG

2021-11-24 12:12 UTC, w4ll3 commented
Thanks for the PR! Looking good, do you think you could refactor it to be part of the core library as a new function? `generateNonce()` that way we could use it to generate nonces at the backend and in the library itself (check `client.ts:117`)

2021-11-26 00:21 UTC, kdenhartog commented
@w4ll3 I was able to get this updated just now, but I'd consider this still a work in progress at this point because I saw that the `client.test.ts file` is failing one test locally because I wasn't able to figure out how to get the examples folder to consume the new function. In theory the code works, but for whatever reason the notepad example isn't picking up the changes made to the core library. Any suggestions on this?

2021-11-26 01:39 UTC, w4ll3 commented
> @w4ll3 I was able to get this updated just now, but I'd consider this still a work in progress at this point because I saw that the `client.test.ts file` is failing one test locally because I wasn't able to figure out how to get the examples folder to consume the new function. In theory the code works, but for whatever reason the notepad example isn't picking up the changes made to the core library. Any suggestions on this?

Mmmm, that's weird. Works for me. Maybe try deleting `node_modules` (from both lib and example) and rebuild?

2021-11-26 02:08 UTC, kdenhartog commented
Ok seems like the server is working fine now, but still have a test failure occurring for validationPositive case. Do I need to regenerate the test vectors or anything like that since the nonce is being changed?

2021-11-26 16:49 UTC, w4ll3 commented
> Ok seems like the server is working fine now, but still have a test failure occurring for validationPositive case. Do I need to regenerate the test vectors or anything like that since the nonce is being changed?

Actually the test was failing for others reasons, it should be fine now.

2021-11-26 16:50 UTC, w4ll3 requested changes

2021-11-26 16:50 UTC, w4ll3 commented on lib/client.ts
> +}
Please add a blank new line at the end

2021-11-26 16:50 UTC, w4ll3 commented on lib/client.ts
> +}
```suggestion
}

```

2021-11-29 15:04 UTC, w4ll3 approved these changes

2021-11-29 15:11 UTC, wyc approved these changes

2021-11-29 15:54 UTC, merged