Update chaindId to string; Update addresses to EIP-55 format; Add EIP…
spruceid/siwe pull request #51
Opened 2022-03-03 18:40 UTC by theosirian

- Updates `chaindId` to be string
- Updates addresses to follow EIP-55 format
- Add EIP-55 negative parsing case

2022-03-18 12:07 UTC, sbihel reviewed
Could we keep the formatting, the indentation and not try to align columns, so in the future the addition of a single test only adds one line, making the git history clean?

2022-03-21 16:43 UTC, sbihel requested changes

2022-03-22 12:42 UTC, awoie commented on test/parsing_negative.json
> +    "address not eip-55": "service.org wants you to sign in with your Ethereum account:\n0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2\n\nI accept the ServiceOrg Terms of Service: https://service.org/to
Version has to be 1 according to spec (for now and for the defined abnf)

2022-03-22 12:47 UTC, awoie commented on test/parsing_negative.json
> +    "address not eip-55": "service.org wants you to sign in with your Ethereum account:\n0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2\n\nI accept the ServiceOrg Terms of Service: https://service.org/to
an example of non-compliant address is the followiing: `0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2`

2022-04-01 10:23 UTC, w4ll3 commented
adressed at #62

2022-04-01 10:25 UTC, closed without merging